### ISSUE TITLE
According to the readme can not run

### ISSUE THREAD

**Issue by wwxFromTju** [ArthurFirmino/gym-battlesnake#1]
According to the readme can not run, as follows:

`python examples/example_multiagent.py`

`Traceback (most recent call last):
  File "examples/example_multiagent.py", line 8, in <module>
    placeholder_env = BattlesnakeEnv(n_threads=4, n_envs=16)
TypeError: Can't instantiate abstract class BattlesnakeEnv with abstract methods env_method, get_attr, set_attr`

**Comment by ArthurFirmino** [comment]
Looks like this is incompatible with `stable-baselines` since `2.5.1`. Try `pip install stable-baselines==2.5.0`

The plan I currently have for this repo is to move to `Tensorflow 2.0` which has its own implementations of the learning algorithms that `gym-battlesnake` is currently borrowing from `stable-baselines`.
