### ISSUE TITLE
Getting the direction of a predicted action

### ISSUE THREAD

**Issue by xtagon** [ArthurFirmino/gym-battlesnake#5]
Hi,

`action, _ = model.predict(obs)` returns each env's actions from 0-3, and I would like to map the predicted action to it's corresponding direction name in Python, for example 0 might be Up, 1 might be Down, etc.

The problem is, the X and Y coordinates alternate pseudo-randomly based on a hash of the game ID and other info, so those action numbers don't correspond 1 to 1 with a given action name. It's different every time you run a prediction.

Is it possible to get the correct action mapping, or get the orientation from the observation, or something like that, so that I can map them to Up/Down/Left/Right labels?

Thanks in advance

**Comment by ArthurFirmino** [comment]
To get the orientation for each observation we could create a new buffer that we write the orientation to when `writeobs` is called within gamewrapper.cpp:

 - Add `std::vector<uint8_t> ori_;` to `class GameWrapper`
 - Add `ori_.resize(n_models * n_envs);` to its constructor
 - At the end of `writeobs` add `ori_[model_i * n_envs_] = static_cast<uint8_t>(ori);`
 - Add `uint8_t* env_getoripointer(GameWrapper *p, unsigned model_i) {
        return &p->ori_[model_i * p->n_envs_];
    }` in the `extern 'C'` section
 - Add `env_oriptr = wrap_function(gamelib, 'env_getoripointer', ctypes.POINTER(ctypes.c_ubyte), [ctypes.c_void_p,ctypes.c_uint])` to gymbattlesnake.py

Then in python you could you could convert it to a numpy array:
```
oriptr = env_oriptr(self.ptr, agent_i)
oriarray = np.ctypeslib.as_array(oriptr, shape(self.n_envs,))
```
Then `oriarray` should have the orientations for all the environments agent_i is playing at that particular step. First bit on means X is flipped, second bit on means Y is flipped. You could use this array to decode `actions` in `step_async` before the call to `env_step(self.ptr)` since the next step will have a different orientation.

As a note, the orientation randomization is so the training snakes won't take to preferring an arbitrary corner of the board.

**Comment by xtagon** [comment]
Thank you so much for the response! I'll give it a try.

It makes sense that the randomization is there for training, I am just looking for a way to use the model for inference in real games after it is trained.

**Comment by ArthurFirmino** [comment]
Ah I see, I had code for it to work with play.battlesnake.com but it wasn't in any repo and I lost it. To get a trained model to play you just have to build the observations yourself, feed it to the model, and get back the action:
```
action,_ = model.predict(obs)
```
Same `model` as in example_singleagent.py or example_multiagent.py. The action won't be randomly oriented, and you shouldn't have to deal with any of the C++ game code.

`obs` should be a 8 bit unsigned integer array, of length 39x39x6 which is just a flattened array of 6 39x39 2D layers.
```
            layer0: snake health on heads {0,...,100}
            layer1: snake bodies {0,1}
            layer2: segment numbers {0,...,255}
            layer3: snake length >= player {0,1}
            layer4: food {0,1}
            layer5: gameboard {0,1}
```
There is some discussion here about how the layers are put together https://github.com/ArthurFirmino/gym-battlesnake/issues/2, you could also reverse engineer it from `writeobs` in gamewrapper.cpp.

**Comment by xtagon** [comment]
That's helpful, thanks! I was working to reverse engineer the layers from `writeobs` but your comment makes that easier.

The `obs` that comes back from the step function is a 3D array with shape (39, 39, 6), so are you saying that passing a flattened int array instead is what will make it not randomly orient the resulting action?

**Comment by ArthurFirmino** [comment]
Never mind the flattened comment, it is in fact an array of shape (n_envs, 39, 39, 6), so it will probably be (1, 39, 39, 6) in your case.

The game used for training randomized the orientations, the model does not.

**Comment by xtagon** [comment]
Perfect, thanks again for all your help 👍
